# Generated by Django 6.0.6 on 2026-07-04 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text="Data e ora in cui si svolge l'evento."),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Gli eventi non attivi sono nascosti dalla prenotazione.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='price cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(help_text='Numero totale di posti generati per questo evento.'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(help_text='es. "A1", "B12"', max_length=10),
        ),
    ]
