# Generated by Django 6.0.6 on 2026-07-04 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_date_alter_event_is_active_and_more'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('seat',), name='unique_confirmed_reservation_per_seat'),
        ),
    ]
