# Generated by Django 6.0.6 on 2026-07-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, help_text='Breve descrizione opzionale del profilo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numero di telefono opzionale, es. +39 055 1234567', max_length=20),
        ),
    ]
